// flow-typed signature: 5b75ae4f42e13b12b6615567e2056306
// flow-typed version: <<STUB>>/objects-to-csv_v^1.2.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'objects-to-csv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'objects-to-csv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'objects-to-csv/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'objects-to-csv/index' {
  declare module.exports: $Exports<'objects-to-csv'>;
}
declare module 'objects-to-csv/index.js' {
  declare module.exports: $Exports<'objects-to-csv'>;
}
declare module 'objects-to-csv/index.test.js' {
  declare module.exports: $Exports<'objects-to-csv/index.test'>;
}
