import { Kernel } from "./kernel.js";
import { TipoBusquedaEstudianteEnum, EntradaParaBusquedaEstudiante } from "./models/index.js";
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
var appKernel = new Kernel('PHPSESSID=1342ce150c25279f2d61a98b07d77681');
var inputBusqueda = new EntradaParaBusquedaEstudiante();
inputBusqueda.doc_number = "1058847076";
inputBusqueda.nombres = undefined;
inputBusqueda.apellidos = undefined;
inputBusqueda.codigo_programa = undefined;
appKernel.getStudentService().searchStudents(inputBusqueda, TipoBusquedaEstudianteEnum.documento);